alertreciever argo migration to go alongside the app one
operate-first/apps pull request #1115
Opened 2021-10-04 16:00 UTC by Gregory-Pereira

This is the argocd portion that goes alongside the application piece of the migration Normally these both would have been one pr in the new workflow, however, the original pr was started before the change. This addresses Tom's comments in https://github.com/operate-first/apps/issues/1073.

2021-10-04 16:47 UTC, 4n4nd requested changes

2021-10-04 16:47 UTC, 4n4nd commented on argocd/overlays/moc-infra/applications/envs/moc/smaug/cluster-management/alertreceiver.yaml
> +    path: alertreceiver/overlays/moc/zero
I think the new path will be `alertreceiver/overlays/moc/smaug`

2021-10-04 19:05 UTC, 4n4nd commented
looks good :+1: 
Can you squash the commits to one commit?

2021-10-04 19:26 UTC, 4n4nd commented
@Gregory-Pereira could you also dd the `opf-alertreceiver` namespace to the `moc/smaug` kustomization [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml)?

2021-10-05 15:40 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 08b144a792af0be2398a34f09089d6a314ece151 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-71e9e14a-9700-4c74-b172-48bc22b7ae1b/prow-logs/pr-logs/pull/operate-first_apps/1115/pre-commit/1445412619832791040) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1115). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-10-05 21:40 UTC, HumairAK approved these changes
/lgtm
/approve

2021-10-05 21:40 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1115#pullrequestreview-772010736" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-10-05 21:55 UTC, closed without merging

2021-10-05 21:55 UTC, HumairAK commented
following up with another pr instead