updating the alerting rules with prometheus standard and thoth rules
operate-first/apps pull request #1254
Opened 2021-10-29 22:20 UTC by Gregory-Pereira

Addresses Operate-first/apps pr 3 for alerting rules for [Thoth issue 2029](https://github.com/thoth-station/thoth-application/issues/2029)
- [x] defined new thoth-github reciever
- [x] wrote alerting rule to target all thoth related alerts 

Prometheus alerting rule updates:
  - inhibit_rules.source_match, inhibit_rules.source_match_re and inhibit_rules.target_match and inhibit_rules.target_match_re have been depricated, use source_matchers and target_matchers, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#inhibit_rule)
  - route.match and route.match_re have been depricated, use route.matchers, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#route)
  - matches configuration defined, [see docs](https://prometheus.io/docs/alerting/latest/configuration/#matcher)

2021-10-29 22:20 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2021-11-01 03:12 UTC, harshad16 requested changes
`matchers` seems  to have `list` based value.
https://prometheus.io/docs/alerting/latest/configuration/#matcher
please convert all the matches value into list

and 
another minor change on our url.

2021-11-01 03:12 UTC, harshad16 commented on cluster-scope/overlays/prod/common/alertmanager-main-secret.yaml
> +          - url: 'http://github-receiver-service.thoth-infra-prod.svc.cluster.local:9393/v1/receiver'
```suggestion
          - url: 'http://github-receiver.thoth-infra-prod.svc.cluster.local:9393/v1/receiver'
```

I think URL won't have the `-service` 
https://github.com/thoth-station/thoth-application/blob/dd21dab477e85735b4d1b84eec0547d41f9b3430/monitoring/base/github-receiver.yaml#L5

2021-11-04 13:47 UTC, harshad16 reviewed
lgtm
PTAL @4n4nd

2021-12-14 03:52 UTC, 4n4nd commented
@Gregory-Pereira this config manifest is common for all the clusters, and the operator/prometheus version might be different for all of them. I just tested this in the smaug cluster and the `matchers` didn't work. Have you tested this in any other clusters?

2022-01-07 17:13 UTC, harshad16 reviewed
lgtm
cc: @4n4nd can you PTAL now

2022-01-17 13:50 UTC, 4n4nd approved these changes
/lgtm

2022-01-17 13:50 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1254#pullrequestreview-854421098" title="LGTM">4n4nd</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [4n4nd]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-01-17 14:06 UTC, merged