adding grafana dashboards to balrog and thoth argocd dashboard CRD
operate-first/apps pull request #1264
Opened 2021-11-02 17:26 UTC by Gregory-Pereira

Addresses part of [Thoth-station/thoth-application issue 2029](https://github.com/thoth-station/thoth-application/issues/2029):
    - task: [x] create new dashboard crd and update the URL route in the kdef

Related to: [Thoth-station/thoth-application PR 2107](https://github.com/thoth-station/thoth-application/pull/2107/) which created the dashboards in thoth-station in the aws-prod overlay for balrog

Two questions:
    1. Do i have to enable the [group: "integreatly.org", kind: "GrafanaDashboard"] in the [global project](https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/projects/global_project.yaml)?
    2. Are we adding kubeflow, odh, operate-first, thanos, and thoth dashboards, or just the thoth dashboards?

2021-11-02 17:26 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-11-02 17:30 UTC, Gregory-Pereira commented
kustomize build currently failing. When I add `opf-monitoring/dashboards/` in the base kustomization file, I get this error instead: `Error: accumulating resources: may not add resource with an already registered id: integreatly.org_v1alpha1_GrafanaDashboard|~X|argocd`

2021-11-02 17:32 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 82cecf8ac30a43637aef700f48937e43c102a841 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1455587222622310400) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-02 22:23 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | c99eb89793f67150c18eb3d90e194e08a770dafc | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1455661689549623296) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-02 22:23 UTC, Gregory-Pereira commented
waiting on squash until I get confirmation we are no longer using kfdefs.

2021-11-03 17:22 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 55581fff1d2383dc9f93b15e06fcac79732778f5 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1455947430284496896) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-04 13:35 UTC, HumairAK commented
Dashboards need to go here: https://github.com/operate-first/apps/tree/master/grafana/base/dashboards , can you move them?

2021-11-04 13:43 UTC, harshad16 requested changes
There seems to be some confusion.
we wont have any other app on balrog apart from thoth and opf.
please make the suggested changes and remove the files.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/kubeflow/kfp-tekton-user.yaml
> +apiVersion: integreatly.org/v1alpha1
We wont have kubeflow in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/kubeflow/kustomization.yaml
> +---
We wont have kubeflow in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/kustomization.yaml
> +  - odh
```suggestion
  - operate-first
  - thoth-station
```

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/odh/jupyterhub-user.yaml
> +apiVersion: integreatly.org/v1alpha1
We won't have odh in balrog, please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/odh/kustomization.yaml
> +---
We wont have odh in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/operate-first/argocd.yaml
> +  name: argocd
We won't have argocd in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/operate-first/opf-availability.yaml
> +  name: opf-availability
We wont have opf-availabilty in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/operate-first/opf-cloud-flowchart.yaml
> +  name: opf-cloud-flowchart
We wont have opf-cloud-flowchart in balrog,please remove this.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/thanos/kustomization.yaml
> +apiVersion: kustomize.config.k8s.io/v1beta1
We wont have thanos deployment in balrog,as we are using the openshift-monioring
please remove the whole sub-dir thanos.

2021-11-04 13:43 UTC, harshad16 commented on grafana/overlays/moc/balrog/opf-monitoring/dashboards/thoth-station/argocd.yaml
> +    version: v4
Make all thoth version to v1

2021-11-04 16:03 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 42d09bcf64f054e411eab307f75f09b585c8d6a2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1456289807545143296) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-04 16:11 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | b942d42b907d67a41ed917c3601242b4c7e615e9 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1456291926088093696) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-04 17:29 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 9b0f9406192e62fab481b3f4387f36e0cc7521d9 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/kustomize-build/1456312503343517696) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-04 17:42 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 3d95ddcd98f2a4d04dccda3bb8772c93da10c3f1 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1264/pre-commit/1456314534644944896) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1264). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-04 17:50 UTC, harshad16 requested changes
lgtm
one change needed

2021-11-04 17:50 UTC, harshad16 commented on grafana/overlays/moc/smaug/dashboards/thoth-station/prod/common-patch.yaml
> +  value: Thoth-Station
please renmae this to 
```suggestion
  value: Thoth-Station-Prod
```

As the same folder would cause collision between moc and prod dashboards.

2021-11-06 19:21 UTC, harshad16 reviewed
lgtm
thanks :100:

2021-11-15 20:18 UTC, HumairAK approved these changes
/lgtm
/approve

2021-11-15 20:19 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1264#pullrequestreview-806507993" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-15 20:39 UTC, merged