added camel-k operator
operate-first/apps pull request #1315
Opened 2021-11-12 09:44 UTC by durandom

to the smaug cluster

I clicked install at https://operatorhub.io/operator/camel-k and added the contents of https://operatorhub.io/install/camel-k.yaml

anything more needed?

fixes https://github.com/operate-first/support/issues/476

2021-11-12 09:44 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **durandom** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2021-11-12 09:45 UTC, sesheta commented
@durandom: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 5f4a09f04205e3638ac6c80931c4495dcd6f07ed | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1315/kustomize-build/1459094810504728576) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1315). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Adurandom). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-11-12 15:40 UTC, 4n4nd requested changes
1. The subscription needs to be added in the [base](https://github.com/operate-first/apps/tree/master/cluster-scope/base/operators.coreos.com/subscriptions).
2. The patch generally contains the stuff that is different from the base, in case of operator subscriptions it is usually the `spec.channel` that is different.

2021-11-24 10:18 UTC, tumido requested changes

2021-11-24 10:18 UTC, tumido commented on cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml
> +  namespace: operators
This namespace doesn't exist. I think you wanted to use `openshift-operators` instead. It's also generally better to enforce the namespace via `kustomization.yaml` (see this [Kiali example here](https://github.com/operate-first/apps/blob/master/cluster-scope/base/operators.coreos.com/subscriptions/kiali-operator/kustomization.yaml)).

2021-11-24 10:18 UTC, tumido commented on cluster-scope/base/operators.coreos.com/subscriptions/camel-k/subscription.yaml
> +  source: operatorhubio-catalog
I don't think we have such catalog available here. In operator hub we have 2 options how to install camel-k:

1. comminuty version of the operator named `camel-k` from `community-operators` catalog
2. redhat certified version with name `red-hat-camel-k` from `redhat-operators` catalog

Based on channel selected I think you wanted to use `community-operators` catalog.

You may also consider updating the channel to `stable-1.7`


These are your options (package name and the catalog can be seen in the URL)

Either community operator:
![image](https://user-images.githubusercontent.com/7453394/143219320-1571f040-ccb1-49f0-b0d7-78102d9bbf00.png)

Or the Red Hat version of it:
![image](https://user-images.githubusercontent.com/7453394/143219439-bc682e94-018c-408f-a536-29e2a3e350ad.png)

2021-11-24 11:19 UTC, durandom commented
@tumido thanks 💯 that was a decent review. I addressed the comments

2021-11-24 11:37 UTC, tumido approved these changes
/lgtm
/approve

2021-11-24 11:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1315#pullrequestreview-814775941" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-11-24 11:44 UTC, merged