Add kyverno deployment to app root
operate-first/apps pull request #1427
Opened 2021-12-09 19:38 UTC by screeley44

Adding in deployment, SA, Services, policy and config maps to the app root for kyverno

2021-12-09 19:38 UTC, sesheta commented
Hi @screeley44. Thanks for your PR.

I'm waiting for a [operate-first](https://github.com/orgs/operate-first/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/operate-first/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-12-09 19:41 UTC, screeley44 commented
@HumairAK @harshad16  - how does this look for app root components?

2021-12-09 20:26 UTC, harshad16 requested changes
lgtm
a minor addition needed

2021-12-09 20:26 UTC, harshad16 commented on kyverno/overlays/moc/smaug/kustomization.yaml
> +  - ../../../base
need an empty line at the end.

2021-12-09 20:34 UTC, screeley44 commented on kyverno/overlays/moc/smaug/kustomization.yaml
> +  - ../../../base
fixed thanks

2021-12-09 20:43 UTC, harshad16 commented
/ok-to-test

2021-12-09 20:49 UTC, sesheta commented
@screeley44: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 2830e0787be4b26651cab5622413dc2eaebe4d50 | [link](https://prow.operate-first.cloud/view/s3/thoth-backup-zero-112b364f-9d15-4d9a-8ff5-0d98aba5f107/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1427/pre-commit/1469045059033763840) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1427). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Ascreeley44). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-02-21 19:15 UTC, codificat commented
/close
as we are going with `cosigned` instead (#1560)

2022-02-21 19:15 UTC, sesheta commented
@codificat: Closed this PR.

<details>

In response to [this](https://github.com/operate-first/apps/pull/1427#issuecomment-1047165682):

>/close
>as we are going with `cosigned` instead (#1560)


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-02-21 19:15 UTC, closed without merging