add: add reloader manifests
operate-first/apps pull request #1438
Opened 2021-12-13 20:59 UTC by dystewart

Added manifests to apps repo for reloader deployment

2021-12-13 21:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **4n4nd** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @4n4nd` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["4n4nd"]} -->

2021-12-13 21:09 UTC, sesheta commented
@dystewart: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 2c9253b25c02806609f6b966584da7edc9f797d6 | [link](https://prow.operate-first.cloud/view/s3/thoth-backup-zero-112b364f-9d15-4d9a-8ff5-0d98aba5f107/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1438/pre-commit/1470498872743694336) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1438). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Adystewart). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-12-14 14:01 UTC, 4n4nd requested changes
One minor comment about the helm annotations/labels. Other than that it looks good :+1: 
Could you also make sure `pre-commit` passes?

2021-12-15 01:30 UTC, closed without merging

2021-12-15 14:19 UTC, HumairAK commented
@dystewart looks like you needed to rebase