Request for creating the thoth-deployment-examples namespace
operate-first/apps pull request #157
Opened 2021-01-25 18:55 UTC by harshad16

manifest for thoth-deployment-examples namespace
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

cc: @pacospace

2021-01-25 18:55 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **anishasthana** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @anishasthana` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["anishasthana"]} -->

2021-01-25 19:08 UTC, tumido requested changes
I think you forgot to reference this namespace in [`overlays/moc/kustomization.yaml`](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/moc/kustomization.yaml)

2021-01-26 09:37 UTC, pacospace commented
> manifest for thoth-deployment-examples namespace
> Signed-off-by: Harshad Reddy Nalla [hnalla@redhat.com](mailto:hnalla@redhat.com)
> 
> Related-to: [thoth-station/elyra-aidevsecops-tutorial#17](https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/17)
> 
> cc: @pacospace

Related: https://github.com/thoth-station/elyra-aidevsecops-tutorial/issues/26

2021-01-26 12:56 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/adrienverge/yamllint.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Passed
Trim Trailing Whitespace.................................................Passed
Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing odh/overlays/moc/monitoring/dashboards/operate-first/argocd.yaml

Check for added large files..............................................Passed
Check for case conflicts.................................................Passed
Check JSON...........................................(no files to check)Skipped
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
yamllint.................................................................Passed
```
</details>

2021-01-26 12:57 UTC, tumido approved these changes
LGTM :+1:

2021-01-26 12:57 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/157#pullrequestreview-576321594" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-26 13:43 UTC, anishasthana approved these changes

2021-01-26 13:43 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/157#pullrequestreview-576357316" title="Approved">anishasthana</a>*, *<a href="https://github.com/operate-first/apps/pull/157#pullrequestreview-576321594" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [anishasthana,tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-01-26 13:43 UTC, merged