feat(onboarding): Add team sostrades
operate-first/apps pull request #1847
Opened 2022-04-04 14:24 UTC by sostrades-dpeltre

Pull request following the guide 'How to onboard a new project to a cluster on Operate First Cloud' to integrate SosTrades Project in Operate-first.

2022-04-04 14:26 UTC, sesheta commented
Hi @sostrades-dpeltre. Thanks for your PR.

I'm waiting for a [operate-first](https://github.com/orgs/operate-first/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/operate-first/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2022-04-04 16:13 UTC, HumairAK commented
/hold

2022-04-04 16:22 UTC, HumairAK commented
@sostrades-dpeltre can describe what this project is about? 

@erikerlandson @caldeirav @redmikhail : are we handing out access to ocp console/namespaces for the osc-cl1/osc-cl2 clusters?

2022-04-05 16:10 UTC, erikerlandson requested changes

2022-04-05 16:25 UTC, HumairAK commented on cluster-scope/overlays/prod/osc/osc-cl1/kustomization.yaml
> -resources:
this is an automated process that is reformatting the file (probably someone manually changed it and the automated tool is changing it back) it's expected

2022-04-05 16:45 UTC, erikerlandson commented
/lgtm

2022-04-05 16:45 UTC, erikerlandson approved these changes

2022-04-05 16:47 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1847#pullrequestreview-932207416" title="Approved">erikerlandson</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **larsks** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @larsks` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["larsks"]} -->

2022-04-05 16:47 UTC, erikerlandson commented
@HumairAK   we are handing out namespaces to projects that need to run services, on a case by case basis.  I am unfamiliar with this particular project, so @caldeirav or @MichaelTiemannOSC  might know if they approved this.

2022-04-05 19:49 UTC, MichaelTiemannOSC commented
sos-trades is a 6-repo contribution fromt Airbus for their "System of Systems" (SOS) platform.  See https://github.com/os-climate/sostrades-core

This is one of two key namespaces needed for Airbus (the other being WITNESS).

2022-04-05 20:01 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-04-05 20:01 UTC, HumairAK commented
/lgtm
/approve

2022-04-05 20:01 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1847#pullrequestreview-932207416" title="Approved">erikerlandson</a>*, *<a href="https://github.com/operate-first/apps/pull/1847#issuecomment-1089268761" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-05 20:45 UTC, HumairAK commented
/unhold

2022-04-05 20:45 UTC, merged

2022-04-06 08:45 UTC, sostrades-dpeltre commented
Thank you @HumairAK for accepting the pull request.
Here is a description of the project : SoSTrades is the tool used for the implementation of WITNESS or Transition Tool within OS-Climate. We plan to connect with Pysical risk and Data commons in the near future. SoSTrades is a web-based, multi-user, interactive publication-quality graph simulation platform. It allows users to drop new modules without additional coding, and provides embedded advanced numerical capabilities for simulation and multi-disciplinary optimization. It also has built-in collaborative capabilities to allow different experts to work together.