manage the kafka for balrog cluster via operate-first
operate-first/apps pull request #1853
Opened 2022-04-04 21:04 UTC by harshad16

manage the kafka for balrog cluster via operate-first
Signed-off-by: Harshad Reddy Nalla <hnalla@redhat.com>

- Reduced the resource for opf-kafka, as it not being to its capacity as of now.
- set all the manifest for kafka w.r.t balrog setup

2022-04-04 21:04 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **harshad16** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-04-04 21:06 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | d48d0ad7d3ed785b1a90c776f683d899c0751616 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1853/kustomize-build/1511087809711050752) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1853). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-04 21:13 UTC, sesheta commented
@harshad16: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | e1ace421c35935e9ffcaf382a34a36d81848fc69 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1853/kustomize-build/1511089049547313152) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1853). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Aharshad16). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-05 13:40 UTC, 4n4nd requested changes

2022-04-05 13:40 UTC, 4n4nd commented on kafka/overlays/balrog/topics/balrog-cluster-audit-logs.yaml
> +  name: balrog-prod.cluster-logs.audit
I don't think the cluster logging topics are needed in the balrog cluster

2022-04-05 13:40 UTC, 4n4nd commented on kafka/overlays/balrog/opf-kafdrop.yaml
> +            secretName: opf-kafka-cluster-ca-cert
the kafka cluster name and secrets names might have changed

2022-04-06 19:38 UTC, harshad16 commented
Thanks for the review, made all the change
Ready for review again

2022-04-07 16:39 UTC, harshad16 commented on kafka/overlays/balrog/opf-kafdrop.yaml
> +            secretName: odh-message-bus-cluster-ca-cert
the secrets are created via the kafka

2022-04-08 13:52 UTC, HumairAK commented
/lgtm

2022-04-08 13:53 UTC, HumairAK commented
@4n4nd can you approve if you are good with the changes

2022-04-08 13:55 UTC, 4n4nd approved these changes
/lgtm

2022-04-08 13:55 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1853#pullrequestreview-936478165" title="LGTM">4n4nd</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [4n4nd]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-08 14:07 UTC, merged