Adding service monitors for Trino and seldon to expose their metrics to prometheus.
operate-first/apps pull request #1908
Opened 2022-04-18 19:44 UTC by mubariskhan96

Introducing the servicemonitors for Trino and Seldon that expose their metrics to prometheus. Re: https://github.com/operate-first/apps/issues/1677

2022-04-18 19:44 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **harshad16** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @harshad16` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2022-04-18 19:46 UTC, mubariskhan96 commented
/cc @4n4nd

2022-04-20 16:12 UTC, 4n4nd requested changes

2022-04-20 19:51 UTC, mubariskhan96 commented on kfdefs/overlays/moc/smaug/trino/servicemonitor.yaml
> +apiVersion: monitoring.coreos.com/v1
done!

2022-04-20 19:52 UTC, mubariskhan96 commented on kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
> +  - port: metrics
Hm, I looked it up again and I cant seem to find the port it is using for exposing metrics to prometheus. Will get back on this later

2022-04-20 19:54 UTC, sesheta commented
@mubariskhan96: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | cccc4b3df875957636e31ad1e7c61e092a3f44d2 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/operate-first_apps/1908/kustomize-build/1516867170007519232) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=1908). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Amubariskhan96). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-21 03:16 UTC, 4n4nd commented on kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
> +  - port: metrics
you can change the port to `http` instead of `metrics`

2022-04-21 14:15 UTC, mubariskhan96 commented on kfdefs/overlays/moc/smaug/seldon/servicemonitor.yaml
> +  - port: metrics
done, thanks!

2022-04-21 17:19 UTC, 4n4nd approved these changes
/lgtm

2022-04-21 17:19 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/1908#pullrequestreview-948957831" title="LGTM">4n4nd</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [4n4nd]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-04-21 17:21 UTC, merged