Added avrajath to cluster admin
operate-first/apps pull request #2011
Opened 2022-05-23 21:18 UTC by AvRajath

Currently a summer intern in Heidi's Team. Hence making a request.

2022-05-23 21:18 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **durandom** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @durandom` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2022-05-25 15:44 UTC, larsks commented
@AvRajath can you provide details on why you need cluster admin access? Most changes to this cluster are made through this apps repository. Would a read-only admin role be sufficient for what you need to do?

2022-06-06 14:04 UTC, larsks commented
@AvRajath generally we don't hand out cluster-admin access (for the most part, any actions that require admin access should be performed by pull requests against the appropriate configuration repository). We do have a read-only admin role that might be appropriate. Would that work out for you?

2022-06-06 14:11 UTC, skanthed commented
@larsks he don’t need cluster admin access on curator. He already has it. I think this is the wrong PR. This PR was for having access on smaug cluster for specific namespace. @AvRajath right?

2022-06-06 14:12 UTC, gagansk commented
@larsks Yes. You can provide @AvRajath cluster-admin access to the `curator` cluster.

2022-06-06 14:19 UTC, larsks commented
@skanthed  this PR is for curator cluster admin access (see the modified files).

2022-06-06 14:22 UTC, skanthed commented
Yes. I saw it. That’s the reason I am saying. It’s the wrong modification. He is already able to access everything on curator. He needed it on Smaug. Maybe he can close this one and create another one for smaug @AvRajath

2022-06-06 14:24 UTC, larsks commented
@AvRajath if you do create a new PR for smaug, then what I said in [an earlier comment](https://github.com/operate-first/apps/pull/2011#issuecomment-1147483654) applies. There is an "sre"  group that has read-only admin access that may be appropriate.

2022-06-07 19:57 UTC, skanthed commented
He need curator access in curator group in smaug. No general access.

2022-06-07 20:39 UTC, dystewart requested changes

2022-06-07 20:39 UTC, dystewart commented on cluster-scope/base/user.openshift.io/groups/curator/group.yaml
> +  - avrajath
@AvRajath Adding github handle here will be sufficient for curator access in smaug

2022-06-07 20:39 UTC, dystewart commented on cluster-scope/overlays/prod/moc/curator/groups/cluster-admins.yaml
> +  - avrajath
@AvRajath Remove your github handle from this this group

2022-06-07 20:59 UTC, dystewart commented
@AvRajath can you squash your commits into 1?

2022-06-08 02:35 UTC, AvRajath commented
> @AvRajath can you squash your commits into 1?

Squashed into a single commit.

2022-06-08 13:21 UTC, HumairAK commented
/lgtm
/approve

2022-06-08 13:21 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/2011#issuecomment-1149907942" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-06-08 13:24 UTC, merged