setup argocd for chris-project
operate-first/apps pull request #2025
Opened 2022-06-01 21:24 UTC by shreekarSS

Signed-off-by: Shreekar <sshreeka@redhat.com>

2022-06-01 21:26 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2022-06-02 11:20 UTC, harshad16 requested changes
Good start
some of the bits are missing, please address them:

- argocd console auth access
https://www.operate-first.cloud/apps/content/argocd-gitops/onboarding_to_argocd.html#enable-openshift-auth-to-argocd-console
https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/configs/argo_cm/dex.config#L11

- adding the permission is needed
https://www.operate-first.cloud/apps/content/argocd-gitops/onboarding_to_argocd.html#give-team-read-access-to-non-app-argocd-resources
https://github.com/operate-first/apps/blob/master/argocd/overlays/moc-infra/configs/argo_rbac_cm/policy.csv

2022-06-02 11:20 UTC, harshad16 commented on argocd/overlays/moc-infra/projects/chris-project.yaml
> +      kind: Namespace
can please remove this bit.

2022-06-02 13:57 UTC, HumairAK commented
duplicate of: https://github.com/operate-first/apps/pull/2026/files

2022-06-02 13:57 UTC, closed without merging