feat(service-catalog): Add clusterrolebinding and clusterrole required for k8s plugin in backstage
operate-first/apps pull request #2156
Opened 2022-07-19 12:30 UTC by SamoKopecky

Part of [#12](https://github.com/operate-first/service-catalog/issues/12)

Backstage k8s plugin requires `clusterrole` for proper functionality. See docs [here](https://backstage.io/docs/features/kubernetes/configuration#role-based-access-control).

2022-07-19 12:31 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **gregory-pereira** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @gregory-pereira` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gregory-pereira"]} -->

2022-07-19 13:18 UTC, tumido requested changes
Cluster role and binding are not pulled into any cluster, please list them in overlays.

2022-07-19 15:19 UTC, SamoKopecky commented
> Cluster role and binding are not pulled into any cluster, please list them in overlays.

Added in the latest commit.

2022-07-20 11:21 UTC, tumido reviewed
I'm unsure about `metrics.k8s.io`.. can you please explain that one to me?

2022-07-20 12:30 UTC, SamoKopecky commented on cluster-scope/base/rbac.authorization.k8s.io/clusterroles/service-catalog-k8s-plugin/clusterrole.yaml
> +  - pods
I ran into an issue while I was testing the k8s plugin out and when supply values for `dashboardUrl` and `dashboardApp` in the [`app-config.yaml`](https://github.com/operate-first/service-catalog/blob/5bc16fceb85ce379f993f8d39c0dd7f2ffae5b56/app-config.yaml#L114-L115) I get the following error:
```
error action=retrieveObjectsByServiceId service=Service1, error=HttpError: HTTP request failed type=plugin
```

I wasn't able to track down why it throws this error, but when I tried to pass an admin SA to the plugin it worked fine. I eventually discovered that insufficient permissions for pods in the `metrics.k8s.io` apiGroup is what was causing the issue.

But I am not really sure how the `metrics.k8s.io` apiGroup connects to the dashboard configuration.

2022-07-20 13:17 UTC, tumido approved these changes
/lgtm
/approve

2022-07-20 13:39 UTC, merged