Add prow test pods namespace
operate-first/apps pull request #216
Opened 2021-02-06 21:24 UTC by goern

This is an additional namespace to separate Prow and its component from the Pods run by jobs...

2021-02-06 21:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-02-08 13:34 UTC, tumido requested changes

2021-02-08 13:34 UTC, tumido commented on cluster-scope/base/namespaces/opf-ci-prow/namespace.yaml
> +kind: Namespace
Please don't define multiple resources in a single file. Please read:

https://github.com/operate-first/apps/blob/master/cluster-scope/README.md

and put this new namespace in `cluster-scope/base/namespaces/opf-ci-test-pods`

You can use the [`hack/onboarding.sh` script](https://github.com/operate-first/apps/blob/master/hack/onboarding.sh)

2021-02-08 14:02 UTC, anishasthana requested changes
Please clean up the commits as well :-)

2021-02-08 18:45 UTC, goern commented
replaced by #221 https://github.com/operate-first/apps/pull/221

2021-02-08 18:45 UTC, closed without merging