installing the loki operator using OCP-nerc-configs methodology
operate-first/apps pull request #2569
Opened 2022-10-17 13:57 UTC by Gregory-Pereira

installing the loki operator using knowledge transfer from nerc

2022-10-17 13:58 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from gregory-pereira by writing `/assign @gregory-pereira` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gregory-pereira"]} -->

2022-10-17 13:59 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 2c87de5bf217bf3593d7d6f46c8d223d44589698 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/pre-commit/1582008185093361665) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:40 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 5cefe72820fef03401a0a7b60ca56c5a54d8a47a | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582380715671031808) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:46 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | db60f0d3976455a13a98c3bbcda483c0e0136333 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582382114425278464) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:50 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | db60f0d3976455a13a98c3bbcda483c0e0136333 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582382114425278464) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | db60f0d3976455a13a98c3bbcda483c0e0136333 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582382114425278465) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:53 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | db60f0d3976455a13a98c3bbcda483c0e0136333 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582382114425278465) | true | `/test kubeval-validation`
aicoe-ci/prow/kustomize-build | 84837e18732f3dbb3f08bd0f0a141aa2bfdd228b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582383944907624448) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:55 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 84837e18732f3dbb3f08bd0f0a141aa2bfdd228b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582383944907624448) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 84837e18732f3dbb3f08bd0f0a141aa2bfdd228b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582383945238974464) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 14:58 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | 84837e18732f3dbb3f08bd0f0a141aa2bfdd228b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582383945238974464) | true | `/test kubeval-validation`
aicoe-ci/prow/kustomize-build | 1d95b930314c177f9c1dda913d1d137157309e72 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582385292067737600) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-18 15:00 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 1d95b930314c177f9c1dda913d1d137157309e72 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1582385292067737600) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 1d95b930314c177f9c1dda913d1d137157309e72 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582385292084514816) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-20 14:31 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | 1d95b930314c177f9c1dda913d1d137157309e72 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1582385292084514816) | true | `/test kubeval-validation`
aicoe-ci/prow/kustomize-build | 46ab17b1b4c99c08fe0eb4b93423aa62681598da | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1583103332514271232) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-24 14:35 UTC, Gregory-Pereira commented
bump @HumairAK 
/cc @durandom

2022-10-24 14:44 UTC, HumairAK commented
Have we checked with NERC folks to see why cluster [rbac](https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/loki/base/clusterrolebindings) is in the `loki` folder and not their [cluster-scope](https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/cluster-scope/base/rbac.authorization.k8s.io) folder? This seems anti-pattern for the current set up (for both operate-first and nerc) 

@larsks any thoughts?

2022-10-24 15:04 UTC, Gregory-Pereira commented
> Have we checked with NERC folks to see why cluster [rbac](https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/loki/base/clusterrolebindings) is in the `loki` folder and not their [cluster-scope](https://github.com/OCP-on-NERC/nerc-ocp-config/tree/main/cluster-scope/base/rbac.authorization.k8s.io) folder? This seems anti-pattern for the current set up (for both operate-first and nerc)

Thanks for the reminder I forgot about this. Hopefully we can get some input from Lars here, but if he doesn't happen to see it, I have also [put this question to the NERC team](https://massopencloud.slack.com/archives/C027TDE52TZ/p1666623728336859) in the MOC slack.

2022-10-31 14:53 UTC, Gregory-Pereira commented
/retest

2022-10-31 16:09 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 824bdb84226f11d58deec16ff06adf5ab5c7f13a | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1587114089560150016) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-31 16:13 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 824bdb84226f11d58deec16ff06adf5ab5c7f13a | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kustomize-build/1587114089560150016) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 824bdb84226f11d58deec16ff06adf5ab5c7f13a | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1587114091707633664) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-31 16:23 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | eb18bc15765136fb5d7082837cd0f8d56d857d3b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/pre-commit/1587117748725485568) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-31 16:29 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | 6362c7b0552fe4b6652427f8b2f9ebc49b47519c | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2569/kubeval-validation/1587119112708952064) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2569). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-15 13:13 UTC, durandom reviewed
looks overall correct to me. see the grafana comment

2022-12-15 13:13 UTC, durandom commented on grafana/overlays/emea/jerry/kustomization.yaml
> +  - ../../../base
dont you need to include this kustomization in the jerry deployments?
And I don't know if we have the grafana operator deployed on jerry

2022-12-15 14:02 UTC, tumido requested changes

2022-12-15 14:02 UTC, tumido commented on cluster-scope/base/rbac.authorization.k8s.io/clusterrolebindings/loki/kustomization.yaml
> +  - lokistack-tenant-logs.yaml
Please use the pattern we always use and don't create new ones. Read this readme please:

https://github.com/operate-first/apps/tree/master/cluster-scope#application-folder-structure

Each resource has it's own folder. If you need to bundle resources together, you can create new bundle in `clsuter-scope/bundles`.

2023-04-14 15:26 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-05-28 03:10 UTC, closed without merging