updating cluster-logging operator base and creating jerry overlay
operate-first/apps pull request #2581
Opened 2022-10-25 13:34 UTC by Gregory-Pereira

Signed-off-by: greg pereira <grpereir@redhat.com>

corresponds to: https://github.com/OCP-on-NERC/nerc-ocp-config/pull/70
Addresses part 2 of: https://github.com/operate-first/apps/issues/2493

2022-10-25 13:35 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from gregory-pereira by writing `/assign @gregory-pereira` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gregory-pereira"]} -->

2022-10-25 13:37 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 266dd0238f9b46e02021175a3ecb679881bbde13 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/kustomize-build/1584901412603564032) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2581). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-10-25 13:38 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 266dd0238f9b46e02021175a3ecb679881bbde13 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/kustomize-build/1584901412603564032) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 266dd0238f9b46e02021175a3ecb679881bbde13 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/kubeval-validation/1584901412624535552) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2581). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-05 15:49 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 91838054ebe7a07799c5218950a8957fb1342ef4 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/pre-commit/1599792789313294336) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2581). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-05 15:51 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 91838054ebe7a07799c5218950a8957fb1342ef4 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/pre-commit/1599792789313294336) | true | `/test pre-commit`
aicoe-ci/prow/kubeval-validation | 91838054ebe7a07799c5218950a8957fb1342ef4 | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2581/kubeval-validation/1599792788633817088) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2581). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-15 13:15 UTC, durandom reviewed
also looks right to me. 
do you want this merged?

2022-12-15 13:59 UTC, tumido requested changes

2022-12-15 13:59 UTC, tumido commented on cluster-logging/overlays/emea/jerry/kustomization.yaml
> +  - ../../../../cluster-scope/base/operators.coreos.com/subscriptions/elasticsearch-operator/
Please don't reference cross application. If manifests are part of the `cluster-scope` root folder, don't reference them from outside of the `cluster-scope`.

2023-03-15 15:24 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2023-04-14 15:26 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-05-28 03:10 UTC, closed without merging