master
operate-first/apps pull request #2593
Opened 2022-11-03 15:56 UTC by durandom

- copy from https://github.com/odh-highlander/nfs-server-and-provisioner/tree/7179cfaf02aa72b6291d6f084123313003141e69
- adapt to operate first layout

2022-11-03 15:58 UTC, durandom commented
@guimou please review. 
The first commit is just verbatim copy from https://github.com/odh-highlander/nfs-server-and-provisioner/tree/7179cfaf02aa72b6291d6f084123313003141e69
So you can just start at the second commit

2022-11-07 18:46 UTC, durandom commented
@Gregory-Pereira PTAL
Except for the argocd-app this is already deployed like this on smaug

2022-11-08 15:53 UTC, Gregory-Pereira reviewed
excellent stuff here, I just had some notes but its almost ready.

/lgtm

2022-11-08 15:53 UTC, Gregory-Pereira commented on cluster-scope/base/core/namespaces/nfs-server-and-provisioner/namespace.yaml
> +  name: dex
This name should not be dex
```suggestion
  name: nfs-provisioner
```

2022-11-08 16:28 UTC, guimou commented on cluster-scope/base/security.openshift.io/securitycontextconstraints/nfs-server-and-provisioner/securitycontextconstraints.yaml
> +  annotations: null
Tbh I never tested removing it. It was like this in the original work from the sig group.

2022-11-08 16:37 UTC, guimou commented on nfs-server-and-provisioner/base/deployment.yaml
> +          image: k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.1
You can check at: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/sig-storage/nfs-provisioner
But you cannot do a direct call on gcr.io repos, like doing a `https://k8s.gcr.io/sig-storage/nfs-provisioner`, it's not like quay or dockerhub.
If you want to try, `podman pull k8s.gcr.io/sig-storage/nfs-provisioner:v3.0.1` works perfectly.

2022-11-09 19:26 UTC, durandom commented on cluster-scope/base/core/namespaces/nfs-server-and-provisioner/namespace.yaml
> +  name: dex
good catch

2022-11-09 19:28 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2022-11-09 19:28 UTC, durandom commented
@Gregory-Pereira I adressed your review, thanks.

2022-11-14 15:52 UTC, tumido requested changes
Other than the cluster scoped resources which have to be moved to `cluster-scope` folder, all seems good.

2022-11-14 15:52 UTC, tumido commented on nfs-server-and-provisioner/base/rbac.yaml
> +kind: ClusterRole
This should go to `cluster-scope` since it's a resource that is cluster scoped and requires cluster admin permissions to apply.

2022-11-14 15:52 UTC, tumido commented on nfs-server-and-provisioner/base/rbac.yaml
> +kind: ClusterRoleBinding
This should go to `cluster-scope` since it's a resource that is cluster scoped and requires cluster admin permissions to apply.

2022-11-14 15:52 UTC, tumido commented on nfs-server-and-provisioner/base/class.yaml
> +kind: StorageClass
This should go to `cluster-scope` since it's a resource that is cluster scoped and requires cluster admin permissions to apply.

2022-11-14 17:59 UTC, durandom commented
@tumido thanks, I addressed your comments in https://github.com/operate-first/apps/pull/2593/commits/c9209cc60622811c184c425fb29c8ed180a92a86

2022-11-15 11:42 UTC, tumido approved these changes
/lgtm
/approve

2022-11-15 11:42 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/2593#pullrequestreview-1180722126" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-11-15 11:44 UTC, merged