Create kuberay operator deployment
operate-first/apps pull request #2680
Opened 2022-12-08 02:53 UTC by saadullah01

We want to create kuberay operator deployment. We have created an issue here: https://github.com/operate-first/support/issues/1149

2022-12-08 02:53 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign redmikhail for approval by writing `/assign @redmikhail` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["redmikhail"]} -->

2022-12-08 02:56 UTC, sesheta commented
@saadullah01: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | b57fb101e91a86ccd9c6c5b38b9689bb786c336b | [link](https://prow.operate-first.cloud/view/s3/prow/prow-logs/pr-logs/pull/operate-first_apps/2680/pre-commit/1600685480234455040) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2680). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3Asaadullah01). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-12-08 07:34 UTC, tumido requested changes
Hey! Is there any reason why these manifests are required to live within the `kfdefs` top-level folder and in this repository at all? Is this expected to be owned by the Operate First Ops team? I think these manifests can be freely owned by the Ray BU team in their own repo, or am I missing something?

/cc @erikerlandson @durandom

2022-12-10 07:07 UTC, tumido requested changes

2022-12-10 07:07 UTC, tumido commented on kfdefs/overlays/moc/smaug/ray-bu/manager.yaml
> +      serviceAccountName: kuberay-operator
Where is this Service account defined? I think you're missing a manifest in the PR.😉

2023-03-12 18:24 UTC, sesheta commented
Issues go stale after 90d of inactivity.
Mark the issue as fresh with `/remove-lifecycle stale`.
Stale issues rot after an additional 30d of inactivity and eventually close.

If this issue is safe to close now please do so with `/close`.

/lifecycle stale

2023-04-11 18:26 UTC, sesheta commented
Stale issues rot after 30d of inactivity.
Mark the issue as fresh with `/remove-lifecycle rotten`.
Rotten issues close after an additional 30d of inactivity.

If this issue is safe to close now please do so with `/close`.

/lifecycle rotten

2023-05-16 07:38 UTC, goern commented
closing this, ODH upstream seems to have done a lot of work and moved on..
thanks @saadullah01 
/close

2023-05-16 07:38 UTC, closed without merging