let dex map any group to argocd
operate-first/apps pull request #2689
Opened 2022-12-14 16:39 UTC by durandom

2022-12-14 16:41 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from durandom by writing `/assign @durandom` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["durandom"]} -->

2022-12-15 07:40 UTC, tumido requested changes
one small nit, otherwise LGTM

2022-12-15 07:40 UTC, tumido commented on argocd/overlays/moc-infra/configs/argo_cm/dex.config
> +      insecureCA: true
Please fix the EOF here.

2022-12-15 10:29 UTC, durandom commented on argocd/overlays/moc-infra/configs/argo_cm/dex.config
> +      insecureCA: true
meh, too reliant on my precommit checks

2022-12-15 10:31 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/2689#pullrequestreview-1218964160" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-15 10:52 UTC, merged