Expand Apex!
operate-first/apps pull request #2698
Opened 2022-12-18 11:49 UTC by dave-tucker

This adds two new namespaces:
- apex-qa (for our QA environment)
- apex-monitoring (where we'll be setting necessary prometheus/grafana/jaeger resources to monitor the apex and apex-qa namespaces)

It updates our `apex` ArgoCD application based on a incoming code change, and adds a new `apex-qa` application that handles our staging environment deployment.

2022-12-18 11:54 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign harshad16 for approval by writing `/assign @harshad16` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["harshad16"]} -->

2023-01-02 15:44 UTC, tumido requested changes
Nice! :slightly_smiling_face: I have 2 inline suggestions (the `namespace:` value in `kustomization.yaml` has to match the namesapce you're creating, otherwise all the components listed in `components:` would deploy to wrong namespace)

Also please add the new namespaces after this line here, so the resources are properly discovered by ArgoCD and deployed:
https://github.com/operate-first/apps/blob/5cb916a5b16467e061ba2c1f4c39c19554b96a5b/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml#L24

2023-01-02 15:44 UTC, tumido commented on cluster-scope/base/core/namespaces/apex-monitoring/kustomization.yaml
> +namespace: apex
```suggestion
namespace: apex-monitoring
```

2023-01-02 15:44 UTC, tumido commented on cluster-scope/base/core/namespaces/apex-qa/kustomization.yaml
> +namespace: apex
```suggestion
namespace: apex-qa
```

2023-01-02 16:12 UTC, dave-tucker commented
Thanks @tumido, changes applied.

2023-01-02 16:30 UTC, tumido approved these changes
/lgtm
/approve

2023-01-02 16:30 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/2698#pullrequestreview-1233894573" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-01-02 16:36 UTC, merged