Remove unused resources for EOY
operate-first/apps pull request #2750
Opened 2023-02-28 18:08 UTC by Gregory-Pereira

Based on the End Of Year survey conducted by the wonderful @schwesig, we are removing unused resources and all manifests related to them.

This PR should remove everything from the following projects:
    - boatrockers
    - fybrik-applications
    - ttm-as-a-service
    - ddas-proj
    - chrisproject-dev
    - seraph-platform-mq
    - humair-sandbox (already removed by humair himself)
    - ushift-dev
    - training-model
    - stackrox
    - varangian-test
    - prometheus-anomaly-detector

/cc @tumido, requesting a second set of eyes don't want any breaking changes.
/cc @schwesig I am not sure about the removal of the OCTO apps, I only saw `ushift-dev` and `training-model` listed, although I am not sure if they meant every application in their `octo-ushift-dev` argocd project which would also inclued: `donkey-car`, `keylime`, `cosigned` and the `octo-summit` stuff. Can you touch base with them to figure out if I should remove everything related to OCTO?

2023-02-28 18:09 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please ask for approval from gregory-pereira by writing `/assign @gregory-pereira` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["gregory-pereira"]} -->

2023-02-28 18:14 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 2d634cf7cbfd3fbc8801705fa6833910463e7227 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630631426674135040) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-28 18:16 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 2d634cf7cbfd3fbc8801705fa6833910463e7227 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630631426674135040) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 2d634cf7cbfd3fbc8801705fa6833910463e7227 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630631428351856640) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-02-28 22:29 UTC, schwesig commented
@Gregory-Pereira thank you so much for the work, figuring it out and create this PR.
I will reach out to them and let you know.

2023-02-28 22:50 UTC, schwesig commented
/lgtm

2023-03-01 16:11 UTC, schwesig commented
@Gregory-Pereira yes, to remove
- donkey-car
- keylime
- cosigned
- octo-summit

talked to @MichaelClifford and @cooktheryan 

also, from @sallyom : ok to remove telemetry / demo projects

2023-03-01 16:17 UTC, harshad16 reviewed
/lgtm

:+1:  thanks for the effort

2023-03-01 16:19 UTC, tumido requested changes
There's some `seraph` namespaces left floating around. Can you please remove them as well? :slightly_smiling_face:

2023-03-01 16:19 UTC, tumido commented on cluster-scope/bundles/seraph/kustomization.yaml
> -  - ../../base/core/namespaces/seraph-platform-mq
Please remove all the `seraph` namespaces + user group.

2023-03-01 16:50 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2023-03-01 16:52 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630973856783011840) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 16:53 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630973856783011840) | true | `/test pre-commit`
aicoe-ci/prow/kustomize-build | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630973855105290240) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 16:53 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630973856783011840) | true | `/test pre-commit`
aicoe-ci/prow/kustomize-build | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630973855105290240) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630973855109484544) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 16:56 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630973855105290240) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630973855109484544) | true | `/test kubeval-validation`
aicoe-ci/prow/pre-commit | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630975108363325440) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 16:57 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 09862f08be7143fe568b8957206f9ec1a1ec927c | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630973855105290240) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630975108363325440) | true | `/test pre-commit`
aicoe-ci/prow/kubeval-validation | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630975107943895040) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 17:05 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630975107943895040) | true | `/test kubeval-validation`
aicoe-ci/prow/kustomize-build | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630975107105034240) | true | `/test kustomize-build`
aicoe-ci/prow/pre-commit | 3499553063367b6d46d0a680d2f3e62c9434d047 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/pre-commit/1630977194190704640) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 17:10 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kubeval-validation | 04bf1054d2f7a1a2ebd2d1eb30e248f9da50c6b7 | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630975107943895040) | true | `/test kubeval-validation`
aicoe-ci/prow/kustomize-build | 31733290ebca0544bf1c76e922ff2187db6fef8a | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630977692893450240) | true | `/test kustomize-build`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-01 17:14 UTC, sesheta commented
@Gregory-Pereira: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/kustomize-build | 31733290ebca0544bf1c76e922ff2187db6fef8a | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kustomize-build/1630977692893450240) | true | `/test kustomize-build`
aicoe-ci/prow/kubeval-validation | 31733290ebca0544bf1c76e922ff2187db6fef8a | [link](https://prow.operate-first.cloud/view/s3/prow-c2ac1283-86c7-4ab4-babc-a07c8c4f1f79/prow-logs/pr-logs/pull/operate-first_apps/2750/kubeval-validation/1630977693736505344) | true | `/test kubeval-validation`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=2750). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2023-03-02 18:06 UTC, merged