feat: Add namespace for users service-catalog
operate-first/apps pull request #2752
Opened 2023-03-02 15:34 UTC by mimotej

Adds a namespace for service-catalog webterminal because by design only kubeadmin can create DevWorkspaces in `openshift-terminal` namespace. I went with small quota because each workspace uses roughly 200m so this means we can run roughly 5 terminals at one time which seems to me like good starting point. For now I have also allowed to users who are in `service-catalog` rolebinding to use this namespace.

2023-03-02 15:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
**Once this PR has been reviewed and has the lgtm label**, please assign larsks for approval by writing `/assign @larsks` in a comment. For more information see:[The Kubernetes Code Review Process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process).

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["larsks"]} -->

2023-03-02 15:35 UTC, mimotej commented
/cc @tumido

2023-03-06 10:10 UTC, tumido requested changes
Please update the `kustomization.yaml` for appropriate clusters to propagate this namespace.

2023-03-06 10:27 UTC, tumido commented
@mimotej please rebase

2023-03-06 10:47 UTC, mimotej commented
> @mimotej please rebase

@tumido done

2023-03-06 12:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/2752#pullrequestreview-1326087215" title="LGTM">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2023-03-06 12:25 UTC, merged