feat: Prepare subscription for MOC CNV 4.7 upgrade
operate-first/apps pull request #288
Opened 2021-03-01 12:03 UTC by tumido

We need to prepare CNV manifests to be deployable on OpenShift 4.7

**Do not merge when: 1) autosync on cluster-resources is on, 2) CNV cluster is not yet on OCP 4.7**

Part of: https://github.com/open-infrastructure-labs/ops-issues/issues/21

/hold

2021-03-01 12:03 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-03-01 12:03 UTC, tumido commented
/cc @martinpovolny @larsks @ipolonsk @HumairAK

2021-03-01 14:50 UTC, larsks commented
Should we be opening doc bugs on all the "guessing the channel because there is no explicit documentation" comments?

2021-03-01 15:40 UTC, tumido commented
@larsks I think the benefit of it may be disputable - first of all, we don't have 4.7 cluster available to us yet. The "go-to" install strategy for all OLM operators is to subscribe via UI. And in the OperatorHub UI, all the channels would be listed properly, so there's no "missing pieces" or something for this type of install.

In our case, since we always kinda expect special treatment, we're hitting the limits. :smile: 

There's also some confusion about channels and operator versions mapping to OpenShift releases, since some of the operators are maintaining a channel per OCP release, some operators were initially doing that (and now they seem to be lacking behind) or they already released 5.0, while previously they've followed the OCP release cycle.. it's really disorganized.

For these operators the docs are not clear:
- OpenShift Virtualization (lacking docs for 4.7) - https://github.com/openshift/openshift-docs/issues/29926
- OpenShift Local Storage (lacking channel description in the docs) - https://github.com/openshift/openshift-docs/issues/29927
- OpenShift Container Storage (Their latest release seems to be 4.6 which is suspicious) - I have no idea where to report this. Maybe Here? https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=8377&projectKey=OCSDOCS

2021-03-02 14:08 UTC, anishasthana approved these changes
/lgtm

2021-03-02 14:08 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/288#pullrequestreview-601852531" title="LGTM">anishasthana</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **tumido** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @tumido` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["tumido"]} -->

2021-03-05 13:02 UTC, sesheta commented
@tumido: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-05 13:12 UTC, sesheta commented
New changes are detected. LGTM label has been removed.

2021-03-07 13:02 UTC, sesheta commented
@tumido: PR needs rebase.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

2021-03-08 14:50 UTC, tumido commented
@larsks @HumairAK review please :slightly_smiling_face:

2021-03-08 14:51 UTC, tumido commented
/unhold

2021-03-08 14:59 UTC, HumairAK commented
/lgtm

2021-03-08 14:59 UTC, merged

2021-03-08 15:00 UTC, larsks approved these changes

2021-03-08 15:04 UTC, 4n4nd requested changes
add the local storage operator patch in main kustomize (https://github.com/operate-first/apps/blob/bc7a99bea520544d6b555a58ff308d32a79c7a5d/cluster-scope/overlays/moc/zero/kustomization.yaml#L89)