Add events creator role to sdap.
operate-first/apps pull request #740
Opened 2021-06-11 15:28 UTC by HumairAK

Should resolve: https://github.com/operate-first/support/issues/266

2021-06-11 15:29 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please ask for approval from **humairak** after the PR has been reviewed.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-06-11 15:33 UTC, sesheta commented
@HumairAK: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
aicoe-ci/prow/pre-commit | 8b490f7de80ab29df576075edc532b822419ce29 | [link](https://prow.operate-first.cloud/view/s3/ci-prow-artifacts--024cd900-706c-488d-afb0-d28522131f45/prow-logs/pr-logs/pull/operate-first_apps/740/pre-commit/1403373737704689664) | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=operate-first&repo=apps&pr=740). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AHumairAK). Please help us and [open an issue](https://github.com/operate-first/apps/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2021-06-14 15:55 UTC, tumido requested changes
/hold 

I need to check something

2021-06-14 16:55 UTC, 4n4nd reviewed
/lgtm

2021-06-14 18:20 UTC, tumido approved these changes
/approve
/lgtm

2021-06-14 18:20 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/apps/pull/740#pullrequestreview-683222060" title="LGTM">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fapps).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/apps/blob/master/OWNERS)~~ [tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-06-14 18:35 UTC, tumido commented
/unhold

2021-06-14 18:47 UTC, merged